login/config/routes.rb
Movie::Application.routes.draw do
   resources :films do
     resources :Admins, :AdminSessions do
    get 'create'
    end
   end
     match 'create' => "admin_sessions#create"
   match 'login' => "admin_sessions#new"
   match 'logout' => "admin_sessions#destroy", :as => :logout

    root :to => 'AdminSessions#new'

end

login/app/models/admin.rb
class Admin < ActiveRecord::Base
 acts_as_authentic
  attr_accessible :login, :password, :password_confirmation
  validates_presence_of :password
  validates_confirmation_of :password
end

login/app/models/admin_session.rb
class AdminSession < Authlogic::Session::Base 

  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end

end

login/app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController
 def new  
    @admin_session = AdminSession.new  
 end  
  
  def create  
    @admin_session = AdminSession.new(params[:admin_session])  
    if @admin_session.save  
      flash[:notice] = "Login successful!"  
      redirect_to "http://www.ymail.com" 
    else  
      render :action => :new  
    end  
  end 
  
  def destroy  
    current_admin_session.destroy  
    flash[:notice] = "Logout successful!"  
    redirect_to root_url  
  end 
   def create
    @adm = Admin.new(params[:adm])

    respond_to do |format|
      if @adm.save
        redirect_to "http://www.ymail.com" 
              else
        
      end
    end
  end

   
  def show

  end
end  
  
  
 

login/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
 
helper_method :current_admin
  
  private
  
  def current_admin_session
    return @current_admin_session if defined?(@current_admin_session)
    @current_admin_session = AdminSession.find
  end
  
  def current_admin
    return @current_admin if defined?(@current_admin)
    @current_admin = current_admin_session && current_admin_session.record
  end
   
end

login/app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

login/app/helpers/application_helper.rb
module ApplicationHelper
end

login/app/views/admin_sessions/create.html.erb
<%= form_for(@adm) do |f| %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Password %><br />
    <%= f.password_field :crypted_password %>
  </div>
  <div class="field">
    <%= f.label :Confirm_password %><br />
    <%= f.password_field :confirm_password %>
  </div>
      <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

login/app/views/admin_sessions/kk.html.erb
<h1>login successfull </h1>
<%= link_to 'list', films_path %>

login/app/views/admin_sessions/new.html.erb
<fieldset>
<h1>Login</h1>

<%= form_for @admin_session, :as => :admin_session, :url => { :action => "create" } do |f| %>
   
  <%= f.label :login %><br />
  <%= f.text_field :login %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
  <br />
  <%= f.submit "Login" %><br>
  <%= link_to 'New user' , create_path %>  
<% end %>
</fieldset>

login/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="nav">

</div>

<%= yield %>

</body>
</html>